rvm:
- 2.0.0
branches:
  only:
    - master
before_script:
  - 'RAILS_ENV=test bundle exec rake setup'
script:
  - 'RAILS_ENV=test bundle exec rake spec'
  - 'RAILS_ENV=production bundle exec rake assets:precompile'
