rvm:
- 2.1.5
sudo: false
branches:
  only:
    - master
before_script:
  - "RAILS_ENV=development USE_SQLITE3=1 bundle exec rake setup"
  - "RAILS_ENV=test bundle exec rake db:migrate"
script:
  - "RAILS_ENV=test bundle exec rake spec"
  - "RAILS_ENV=production bundle exec rake assets:precompile"
after_success:
  - "openssl aes-256-cbc -K $encrypted_7a5e0dfbb465_key -iv $encrypted_7a5e0dfbb465_iv -in id_beatech.enc -out ~/.ssh/id_beatech -d"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"
